# Generated by Django 3.0.2 on 2020-02-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aellido_paterno',
            new_name='apellido_paterno',
        ),
    ]
