# Generated by Django 3.0.2 on 2020-02-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20200213_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelestadocivil',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
